name: bimodal
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cffi=1.15.0
  - cpuonly=2.0
  - freetype=2.12.1
  - giflib=5.2.1
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libffi=3.2.1
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtiff=4.4.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - openssl=1.0.2u
  - pillow=9.2.0
  - pip=22.2.2
  - pycparser=2.21
  - python=3.7.0
  - pytorch=1.2.0
  - pytorch-mutex=1.0
  - readline=7.0
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.33.0
  - tk=8.6.12
  - torchvision=0.4.0
  - wheel=0.37.1
  - xz=5.2.8
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - attrs==22.1.0
      - backcall==0.2.0
      - charset-normalizer==2.1.1
      - cycler==0.11.0
      - decorator==5.1.1
      - exmol==2.2.1
