name: bimodal
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pytorch-cpu=1.2.0
  - torchvision=0.4.0
  - matplotlib
  - pillow
  - jupyter
  - pandas
  - scikit-learn
  - scipy
  - pip:
    - exmol==2.2.1
    - attrs==22.1.0
    - backcall==0.2.0
    - cycler==0.11.0
    - decorator==5.1.1
    - ipykernel==6.4.1
    - ipython==7.29.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - joblib==1.1.0
    - jupyter-client==7.1.2
    - jupyter-console==6.4.0
    - jupyter-core==4.9.1
    - matplotlib-inline==0.1.3
    - numpy==1.19.5
    - pandas==1.3.5
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prompt-toolkit==3.1.1
    - ptyprocess==0.7.0
    - pygments==2.11.2
    - python-dateutil==2.8.2
    - pytz==2021.3
    - scikit-learn==1.0.1
    - scipy==1.7.3
    - six==1.16.0
    - threadpoolctl==3.1.0
    - traitlets==5.1.1
    - wcwidth==0.2.5
